### ISSUE TITLE
Test for all types of erroneous energy-generating cycles (EGC)

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#189]
#### Problem description
We're testing for ATP production, but the production of other energy metabolites out of nothing is just as likely. In fact, a recent study [1] outlines just how much this affects non-curated, automatically-generated models. They also list a couple if essential metabolites to test for. We should try to extend our tests to account for them too.

- [1] Fritzemeier, C. J., Hartleb, D., Szappanos, B., Papp, B., & Lercher, M. J. (2017). Erroneous energy-generating cycles in published genome scale metabolic networks: Identification and removal. PLoS Computational Biology, 13(4), 1–14. http://doi.org/10.1371/journal.pcbi.1005494

#### Code Sample
- [ ] Test NADH production in closed state of the model
- [ ] Test NADPH
- [ ] Test CTP
- [ ] Test GTP
- [ ] Test UTP
- [ ] Test ITP
- [ ] Test FAD
- [ ] Test FMN
- [ ] Test Q8H2 (Ubiquinol-8)
- [ ] Test MQL8 (Menaquinol 8)
- [ ] Test 2DMMQL8 (2-Demethylmenaquinol 8)
- [ ] Test ACCOA (Acetyl-CoA)
- [ ] Test GLU__L (L-Glutamate)
- [ ] Test Proton
