### ISSUE TITLE
Checklist for Submission (Cover Letter, Reviewers)

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#275]
This is a work-in-progress checklist of items required for publication.

- [x] Names and affiliations of all co-authors. 
- [x] The primary affiliation for each author should be the institution where the majority of their work was done.
- [x] The corresponding author should be identified with an asterisk.
- [x] If the manuscript includes personal communications, please provide a written statement of permission from any person who is quoted. E-mail permission messages are acceptable.
- [x] Papers submitted to Nature Biotechnology should be accessible to non-specialists; you should ensure that your findings are communicated clearly. (Technical jargon should be avoided as far as possible and clearly explained where its use is unavoidable. Abbreviations should be kept to a minimum and should be defined at their first occurrence. The background, rationale and main conclusions of the study should be clearly explained. Titles and abstracts in particular should be written in language that will be readily intelligible to any scientists.)
- [x] Provide a cover letter to the editors. Indicate whether you have had any prior discussions with a Nature Biotechnology editor about the work described in the manuscript.
- [x] The manuscript text file should include the following parts, in order: a title page with author names, affiliations and contact information (the corresponding author should be identified with an asterisk); the sections required for each content type, then Acknowledgements (optional), Author Contributions, Competing Financial Interests statement, References, Figure Legends, and Tables.
- [x] The manuscript file should be formatted as double-spaced, single-column text without justification
- [x] Acknowledgements should be brief, and should not include thanks to anonymous referees and editors, or effusive comments. Grant or contribution numbers may be acknowledged.
- [x] References are numbered sequentially as they appear in the text, tables, figure legends and online Methods. Only one publication is given for each number. Only papers that have been published or accepted by a named publication or recognized preprint server should be in the numbered list.
- [x] Published conference abstracts, numbered patents and research datasets that have been assigned a digital object identifier may be included in the reference list. URLs for web sites should be cited parenthetically in the text, not in the reference list; articles in formal, peer-reviewed online journals should be included in the reference list.
- [x] Nature Biotechnology uses standard Nature referencing style. All authors should be included in reference lists unless there are more than five, in which case only the first author should be given, followed by 'et al.'. Authors should be listed last name first, followed by a comma and initials (followed by full stops) of given names. Article titles should be in Roman text, the first word of the title should be capitalized and the title written exactly as it appears in the work cited, ending with a full stop.
- [x] Figure legends for Articles or Letters begin with a brief title for the whole figure and continue with a short description of each panel and the symbols used, focusing on describing what is shown in the figure and de-emphasizing methodological details. The meaning of all error bars and how they were calculated should be described. Each legend should total no more than 250 words.
- [x] Please submit tables at the end of your text document (in Word or TeX/LaTeX, as appropriate). Tables that include statistical analysis of data should describe their standards of error analysis and ranges in a table legend.
- [x] Figure lettering should be in a clear, sans-serif typeface (for example, Helvetica); if possible, the same typeface in approximately the same font size should be used for all figures in a paper.
- [x] Figures divided into parts should be labelled with a lower-case bold a, b, and so on, in the same type size as used elsewhere in the figure.
- [x] In legends, please use visual cues rather than verbal explanations, such as "open red triangles".
- [x] Authors are encouraged to consider the needs of colorblind readers (a substantial minority of the male population) when choosing colors for figures. 
- [x] Supplementary information is not copy-edited by Nature Biotechnology, so authors should ensure that it is clearly and succinctly presented, and that the style and terminology conform with the rest of the paper. Please note that modification of supplementary information after the paper is published requires a formal correction, so authors are encouraged to check their supplementary information carefully before submitting the final version.
- [x] The number of Supplementary Figures should not exceed the number of main figures in the article, and each Supplementary Figure should fit one printable 8.5 x 11 inch page. While we would encourage authors to be selective in including as other types of supplemental data, such as Supplementary Tables and Videos, no restrictions will currently apply to these data types.
- [x] Designate each item as Supplementary Table, Figure, Video, Audio, Notes, Data, Discussion or Equations. Number Supplementary Tables and Figures as, for example, "Supplementary Table 1". This numbering should be separate from that used in tables and figures appearing in the main printed article. Supplementary Notes should not be numbered and can have an optional title. Please provide a title for Supplementary Tables and a title and a caption for Supplementary Figures, Supplementary Video and Supplementary Notes.
- [x] Refer to each piece of supplementary information at least once within the text of the main article, at the appropriate point(s). Be sure to include the word "Supplementary" each time one is mentioned. Please do not refer to individual panels of supplementary figures.
- [x] A high priority of Nature Biotechnology is that all papers be accessible to non-specialists. 
- [x] Nature Biotechnology uses American English spelling
- [x] Submission to a Nature Research journal is taken by the journal to mean that all the listed authors have agreed all of the contents, including the author list and author contributions statements. The corresponding author is responsible for having ensured that this agreement has been reached, that all authors have agreed to be so listed and approved the manuscript submission to the journal, and for managing all communication between the journal and all co-authors, before and after publication. Any changes to the author list after submission, such as a change in the order of the authors, or the deletion or addition of authors, needs to be approved by every author.
- [x] The Nature Research journals do not prescribe the kinds of contributions that warrant authorship but encourage transparency by publishing author contributions statements.
- [x] Before submission, the corresponding author ensures that all authors are included in the author list, its order has been agreed by all authors, and that all authors are aware that the paper was submitted.
- [x] At submission, the corresponding author must include written permission from the authors of the work concerned for mention of any unpublished material included in the manuscript, for example others' data, in press manuscripts, personal communications or work in preparation. The corresponding author also must clearly identify at submission any material within the manuscript that has previously been published elsewhere by other authors (for example, figures) and provide written permission from those authors and/or publishers, as appropriate, for the re-use of such material.
- [ ] Authors are welcome to suggest suitable independent reviewers when they submit their manuscripts, but these suggestions may not be followed by the journal. 
- [ ] To facilitate submission of manuscripts with large author lists, please consult the journal editor before submission.

Source:
https://www.nature.com/nbt/for-authors/preparing-your-submission
